
services:
  db_measures_shopper:
    container_name: dev_db
    image: postgres:13
    ports:
      - 4747:5432
    environment:
      POSTGRES_USER: leitor
      POSTGRES_PASSWORD: l31t03
      POSTGRES_DB: leituras
    networks:
      - shopper

  shopper-backend:
    restart: always
    build: .
    ports:
      - 3000:3000
    environment:
    - DATABASE_URL=postgresql://leitor:l31t03@dev_db:5432/leituras?schema=public
    networks:
      - shopper


networks:
  shopper: